---
driver:
  name: vagrant
driver_config:
  customize:
    memory: 1024
    cpus: 4
    cpuexecutioncap: 70

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4
    driver:
      box: debian-7.4.0-amd64-chef-11.12.2
      box_url: https://s3.amazonaws.com/linux-vbox/debian-7.4.0-amd64-chef-11.12.2.box

suites:
  - name: indexer
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash]
    attributes:
      logstash:
        install_types: [indexer]
  - name: agent
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash]
    attributes:
  - name: both
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash]
    attributes:
      logstash:
        install_types: [agent, indexer]
