---
driver:
  name: vagrant
driver_config:
  customize:
    memory: 1024
    cpus: 4
    cpuexecutioncap: 70

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.2.0
    driver:
      box: debian-7.2.0-amd64-chef

suites:
  - name: server
    data_bags_path: <%= ENV['CHEF_DATA_BAGS'] %>
    encrypted_data_bag_secret_key_path: <%= ENV['CHEF_SECRET_FILE'] %>
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash::server]
    attributes:
