---
driver:
  name: vagrant
driver_config:
  customize:
    memory: 1024
    cpus: 4
    cpuexecutioncap: 70

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.4
    driver:
      box: debian-7.4.0-amd64-chef-11.12.2
      box_url: https://s3.amazonaws.com/linux-vbox/debian-7.4.0-amd64-chef-11.12.2.box

suites:
  - name: indexer
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash]
    attributes:
      logstash:
        install_types: [indexer]
        indexer:
          config_input:
            syslog:
              file:
                type: syslog
                path:
                  - /var/log/*.log
                  - /var/log/messages
                  - /var/log/syslog
          config_output:
            es_embedded:
              elasticsearch:
                embedded: true
  - name: agent
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash]
    attributes:
      logstash:
        agent:
          config_input:
            syslog:
              file:
                type: syslog
                path:
                  - /var/log/*.log
                  - /var/log/messages
                  - /var/log/syslog
          config_output:
            logfile:
              file:
                path: /opt/logstash/log/out.log
  - name: both
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash]
    attributes:
      logstash:
        install_types: [agent, indexer]
        indexer:
          config_input:
            syslog:
              file:
                type: syslog
                path:
                  - /var/log/*.log
                  - /var/log/messages
                  - /var/log/syslog
          config_output:
            es_embedded:
              elasticsearch:
                embedded: true
        agent:
          config_input:
            syslog:
              file:
                type: syslog
                path:
                  - /var/log/*.log
                  - /var/log/messages
                  - /var/log/syslog
          config_output:
            logfile:
              file:
                path: /opt/logstash/log/out.log
