---
driver:
  name: vagrant
driver_config:
  customize:
    memory: 1024
    cpus: 4
    cpuexecutioncap: 70

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.2.0
    driver:
      box: debian-7.2.0-amd64-chef

suites:
  - name: indexer
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash::indexer]
    attributes:
  - name: agent
    run_list:
      - recipe[apt::default]
      - recipe[java]
      - recipe[logstash::agent]
    attributes:
